services:
  # A Docker web service
  - type: web
    name: {{cookiecutter.project_slug}}
    env: docker
    buildCommand: .venv/bin/{{cookiecutter.project_slug}} manage migrate --no-input
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: main # optional (defaults to master)
    numInstances: 3 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: {{cookiecutter.project_slug}}-db
          property: connectionString
